title:        
  en: Tats and Tats
  it: Tast e Tats
tagline:          "It's happening"
description:      ""
canonical: https://tatsandtats.github.io

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://tatsandtats.github.io"
baseurl: ""



# Owner/author information
owner:
  name:           Tats
  avatar:         avatar.png
  bio:            ""
  email:          tatsandtats@gmail.com
  #twitter:        twnsndco
  #github:         coletownsend
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  #disqus:         balzac
  #location:       "Buffalo, NY"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
#opengraph:
#  locale:           en_US

# Links to include in top navigation
# For external links add external: true
# might have to change this links to match multilingual site
links:
#  en:
#    home:
#      title: Home
#      url: /
#    where:
#      title: Where
#      url: /where
#    when:
#      title: When
#      url: /when
#    contact:
#      title: Contact
#      url: /contact
#  it:
#    home:
#      title: Homepage
#      url: /casa
#    where:
#      title: Dove
#      url: /dove
#    when:
#      title: Quando
#      url: /quando
#    contact:
#      title: Contatti
#      url: /contatti
    
  - title: Where
    url: /where
  - title: When
    url: /when
  - title: Contact
    url: /contact
  #for registry, add external link if necessary
 # - title: Registry
 #   url: http://www.something.com 
 #   external: true
  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
